const TRANSCRIPTION_WORDS_THRESHOLD = 3;
const TRANSCRIPTION_AUDIO_CHUNK_DURATION = 480; // 8 minutes in seconds
const CLEANUP_RETENTION_DAYS = 14;

module.exports = { TRANSCRIPTION_WORDS_THRESHOLD, CLEANUP_RETENTION_DAYS, TRANSCRIPTION_AUDIO_CHUNK_DURATION };